/**
 * Spec-to-PR — paste a plain-English feature spec, get back a draft PR
 * generated by the Claude API.
 *
 *   GET  /:owner/:repo/spec                          — form (requires write access)
 *   POST /:owner/:repo/spec                          — kicks off background job,
 *                                                       redirects to progress page
 *   GET  /:owner/:repo/spec/:jobId/progress          — live progress page (SSE)
 *   GET  /:owner/:repo/spec/:jobId/progress/events   — SSE event stream
 *   GET  /:owner/:repo/spec/:jobId/status            — JSON status (polling fallback)
 *
 * The backend (`createSpecPR` in `src/lib/spec-to-pr.ts`) is being built in
 * parallel. We import it dynamically so this file compiles and its tests
 * pass even if the module is not yet on disk — if the import fails we
 * fall back to a "Backend not available" banner.
 *
 * 2026 polish: scoped `.specs-*` class system. Eyebrow + display headline +
 * subtitle hero, card sections for the form + the "how this works" steps,
 * primary CTA on the submit button. All form fields, names, actions, and
 * the dynamic-import behaviour are unchanged.
 */
import { Hono } from "hono";
import { and, eq, like } from "drizzle-orm";
import { db } from "../db";
import { repositories, users, issues, pullRequests } from "../db/schema";
import { Layout } from "../views/layout";
import { RepoHeader } from "../views/components";
import { softAuth, requireAuth } from "../middleware/auth";
import type { AuthEnv } from "../middleware/auth";
import { listBranches, getBlob, getTreeRecursive } from "../git/repository";
import {
  AI_SPEC_PR_MARKER,
  parseFrontMatter,
  type SpecStatus,
} from "../lib/spec-to-pr";
import { publish, subscribe } from "../lib/sse";

// ---------------------------------------------------------------------------
// In-memory spec job registry
// ---------------------------------------------------------------------------
// Each background spec run is tracked here from the moment the POST fires
// until it completes (or the server restarts). The Map is keyed by a short
// random job ID that lives in the redirect URL.
//
// Eviction: jobs are kept for 10 minutes after completion so late-arriving
// SSE clients still get a "done" snapshot. The autopilot-ish ticker below
// sweeps stale entries.

export type SpecStage =
  | "queued"
  | "analyzing"
  | "writing"
  | "opening_pr"
  | "done"
  | "error";

export interface SpecJob {
  id: string;
  owner: string;
  repo: string;
  stage: SpecStage;
  label: string; // human-readable stage label
  prNumber: number | null;
  error: string | null;
  startedAt: number; // Date.now()
  completedAt: number | null;
}

const specJobs = new Map<string, SpecJob>();

// Sweep completed jobs older than 10 minutes.
setInterval(() => {
  const cutoff = Date.now() - 10 * 60 * 1000;
  for (const [id, job] of specJobs) {
    if (job.completedAt !== null && job.completedAt < cutoff) {
      specJobs.delete(id);
    }
  }
}, 60_000);

function specJobTopic(jobId: string): string {
  return `spec-job:${jobId}`;
}

/** Advance a job to a new stage and publish the SSE event. */
function advanceStage(job: SpecJob, stage: SpecStage, label: string): void {
  job.stage = stage;
  job.label = label;
  publish(specJobTopic(job.id), {
    event: "stage",
    data: { stage, label, prNumber: job.prNumber, error: job.error },
  });
}

const STAGE_LABELS: Record<SpecStage, string> = {
  queued: "Queued",
  analyzing: "Analyzing spec",
  writing: "Writing code",
  opening_pr: "Opening PR",
  done: "Done",
  error: "Error",
};

/**
 * Run the spec-to-PR pipeline in the background, publishing SSE events at
 * each stage transition. Accepts the same arguments as `createSpecPR`.
 */
async function runSpecJobInBackground(
  job: SpecJob,
  args: { repoId: string; spec: string; baseRef: string; userId: string }
): Promise<void> {
  // Stage 1 — analyzing spec / building context
  advanceStage(job, "analyzing", STAGE_LABELS.analyzing);

  // Dynamically import the backend (same guard as the POST handler).
  let createSpecPR:
    | ((args: {
        repoId: string;
        spec: string;
        baseRef: string;
        userId: string;
      }) => Promise<
        | { ok: true; prNumber: number }
        | { ok: false; error: string }
      >)
    | null = null;
  try {
    const mod: any = await import("../lib/spec-to-pr");
    createSpecPR =
      (mod && (mod.createSpecPR || (mod.default && mod.default.createSpecPR))) ||
      null;
  } catch {
    createSpecPR = null;
  }

  if (!createSpecPR) {
    job.error = "Backend not available — spec-to-PR is not deployed yet.";
    job.completedAt = Date.now();
    advanceStage(job, "error", STAGE_LABELS.error);
    return;
  }

  // Stage 2 — writing code (AI generating). We publish this immediately
  // before the Claude call so the UI shows "Writing code" while we wait.
  advanceStage(job, "writing", STAGE_LABELS.writing);

  let result: { ok: true; prNumber: number } | { ok: false; error: string };
  try {
    result = await createSpecPR(args);
  } catch (err) {
    result = {
      ok: false,
      error: err instanceof Error ? err.message : "Unexpected error",
    };
  }

  if (!result.ok) {
    job.error = result.error;
    job.completedAt = Date.now();
    advanceStage(job, "error", STAGE_LABELS.error);
    return;
  }

  // Stage 3 — opening PR (the insert already happened inside createSpecPR,
  // but we surface this stage as a brief acknowledgement).
  advanceStage(job, "opening_pr", STAGE_LABELS.opening_pr);
  job.prNumber = result.prNumber;

  // Stage 4 — done.
  job.completedAt = Date.now();
  advanceStage(job, "done", STAGE_LABELS.done);
}

const specs = new Hono<AuthEnv>();

// Tiny inline script that disables the submit button + textarea while the
// request is in-flight so users don't accidentally double-click and trigger
// two 10-30s Claude calls. Rendered as a plain <script> tag.
const DISABLE_ON_SUBMIT_JS = `
(function() {
  var form = document.getElementById('spec-form');
  if (!form) return;
  form.addEventListener('submit', function() {
    var btn = form.querySelector('button[type="submit"]');
    var ta = form.querySelector('textarea[name="spec"]');
    if (btn) {
      btn.disabled = true;
      btn.textContent = 'Working… this can take 10-30s';
    }
    if (ta) ta.readOnly = true;
  });
})();
`;

// ─── Scoped CSS (.specs-*) ─────────────────────────────────────────────────
const specsStyles = `
  .specs-wrap { max-width: 1680px; margin: 0 auto; padding: var(--space-5) var(--space-4) var(--space-8); }

  /* ─── Header ─── */
  .specs-head { margin-bottom: var(--space-5); }
  .specs-eyebrow {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    text-transform: uppercase;
    font-family: var(--font-mono);
    font-size: 11px;
    letter-spacing: 0.16em;
    color: var(--text-muted);
    font-weight: 600;
    margin-bottom: 10px;
  }
  .specs-eyebrow-dot {
    width: 8px; height: 8px;
    border-radius: 9999px;
    background: linear-gradient(135deg, #8c6dff, #36c5d6);
    box-shadow: 0 0 0 3px rgba(140,109,255,0.18);
  }
  .specs-pill-experimental {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    padding: 2px 8px;
    margin-left: 4px;
    border-radius: 9999px;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.06em;
    background: rgba(251,191,36,0.12);
    color: #fde68a;
    box-shadow: inset 0 0 0 1px rgba(251,191,36,0.32);
  }
  .specs-title {
    font-family: var(--font-display);
    font-size: clamp(26px, 3.6vw, 40px);
    font-weight: 800;
    letter-spacing: -0.028em;
    line-height: 1.05;
    margin: 0 0 6px;
    color: var(--text-strong);
  }
  .specs-title-grad {
    background-image: linear-gradient(135deg, #a48bff 0%, #8c6dff 50%, #36c5d6 100%);
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
    color: transparent;
  }
  .specs-sub {
    margin: 0;
    font-size: 14px;
    color: var(--text-muted);
    line-height: 1.5;
    max-width: 720px;
  }
  .specs-sub a { color: var(--accent); text-decoration: none; }
  .specs-sub a:hover { text-decoration: underline; }
  .specs-sub code {
    font-family: var(--font-mono);
    font-size: 12px;
    background: rgba(255,255,255,0.04);
    padding: 1px 6px;
    border-radius: 4px;
  }

  /* ─── Banners ─── */
  .specs-banner {
    margin-bottom: var(--space-4);
    padding: 10px 14px;
    border-radius: 10px;
    font-size: 13.5px;
    border: 1px solid var(--border);
    background: rgba(255,255,255,0.025);
    color: var(--text);
    display: flex;
    align-items: flex-start;
    gap: 10px;
    line-height: 1.45;
  }
  .specs-banner.is-info {
    border-color: rgba(54,197,214,0.40);
    background: rgba(54,197,214,0.08);
    color: #cffafe;
  }
  .specs-banner.is-error {
    border-color: rgba(248,113,113,0.40);
    background: rgba(248,113,113,0.08);
    color: #fecaca;
  }
  .specs-banner-dot {
    width: 8px; height: 8px;
    border-radius: 9999px;
    background: currentColor;
    margin-top: 6px;
    flex-shrink: 0;
  }
  .specs-banner a {
    color: inherit;
    text-decoration: underline;
    font-weight: 600;
  }

  /* ─── Section card ─── */
  .specs-section {
    margin-bottom: var(--space-5);
    background: var(--bg-elevated);
    border: 1px solid var(--border);
    border-radius: 14px;
    overflow: hidden;
    position: relative;
  }
  .specs-section::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 2px;
    background: linear-gradient(90deg, transparent 0%, #8c6dff 30%, #36c5d6 70%, transparent 100%);
    opacity: 0.55;
    pointer-events: none;
  }
  .specs-section-head {
    padding: var(--space-4) var(--space-5) var(--space-3);
    border-bottom: 1px solid var(--border);
  }
  .specs-section-title {
    margin: 0;
    font-family: var(--font-display);
    font-size: 16px;
    font-weight: 700;
    letter-spacing: -0.018em;
    color: var(--text-strong);
  }
  .specs-section-sub {
    margin: 6px 0 0;
    font-size: 12.5px;
    color: var(--text-muted);
    line-height: 1.45;
  }
  .specs-section-body {
    padding: var(--space-4) var(--space-5);
  }

  /* ─── Form fields ─── */
  .specs-field { margin-bottom: var(--space-4); }
  .specs-field:last-child { margin-bottom: 0; }
  .specs-field-label {
    display: block;
    font-size: 11.5px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--text-muted);
    margin-bottom: 6px;
  }
  .specs-input,
  .specs-select,
  .specs-textarea {
    width: 100%;
    box-sizing: border-box;
    padding: 10px 12px;
    font: inherit;
    font-size: 13.5px;
    color: var(--text);
    background: rgba(255,255,255,0.03);
    border: 1px solid var(--border-strong);
    border-radius: 10px;
    transition: border-color 120ms ease, background 120ms ease, box-shadow 120ms ease;
  }
  .specs-textarea {
    font-family: var(--font-mono);
    font-size: 13px;
    line-height: 1.55;
    resize: vertical;
    min-height: 200px;
  }
  .specs-input:focus,
  .specs-select:focus,
  .specs-textarea:focus {
    outline: none;
    border-color: rgba(140,109,255,0.55);
    background: rgba(255,255,255,0.05);
    box-shadow: 0 0 0 3px rgba(140,109,255,0.18);
  }
  .specs-select {
    appearance: none;
    padding-right: 30px;
    background-image:
      linear-gradient(45deg, transparent 50%, var(--text-muted) 50%),
      linear-gradient(135deg, var(--text-muted) 50%, transparent 50%);
    background-position: right 12px top 50%, right 7px top 50%;
    background-size: 5px 5px, 5px 5px;
    background-repeat: no-repeat;
  }
  .specs-field-hint {
    margin-top: 6px;
    font-size: 11.5px;
    color: var(--text-muted);
    line-height: 1.45;
  }

  /* ─── Buttons ─── */
  .specs-actions {
    display: flex;
    align-items: center;
    gap: 10px;
    flex-wrap: wrap;
    padding-top: 4px;
  }
  .specs-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    padding: 10px 18px;
    border-radius: 10px;
    font-size: 13.5px;
    font-weight: 600;
    text-decoration: none;
    border: 1px solid transparent;
    cursor: pointer;
    font: inherit;
    line-height: 1;
    white-space: nowrap;
    transition: transform 120ms ease, box-shadow 120ms ease, background 120ms ease, border-color 120ms ease, color 120ms ease;
  }
  .specs-btn-primary {
    background: linear-gradient(135deg, #8c6dff 0%, #36c5d6 100%);
    color: #ffffff;
    box-shadow: 0 6px 18px -6px rgba(140,109,255,0.50), inset 0 1px 0 rgba(255,255,255,0.16);
  }
  .specs-btn-primary:hover {
    transform: translateY(-1px);
    box-shadow: 0 10px 24px -8px rgba(140,109,255,0.60), inset 0 1px 0 rgba(255,255,255,0.20);
    color: #ffffff;
    text-decoration: none;
  }
  .specs-btn-primary:disabled {
    cursor: not-allowed;
    opacity: 0.6;
    transform: none;
    box-shadow: none;
  }
  .specs-actions-hint {
    font-size: 12px;
    color: var(--text-muted);
  }

  /* ─── How-this-works step cards ─── */
  .specs-steps {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 10px;
  }
  .specs-step {
    padding: 14px;
    background: rgba(255,255,255,0.018);
    border: 1px solid var(--border);
    border-radius: 11px;
    transition: border-color 120ms ease, background 120ms ease;
  }
  .specs-step:hover {
    border-color: var(--border-strong);
    background: rgba(255,255,255,0.03);
  }
  .specs-step-num {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 24px; height: 24px;
    border-radius: 7px;
    background: rgba(140,109,255,0.16);
    color: #c4b5fd;
    box-shadow: inset 0 0 0 1px rgba(140,109,255,0.32);
    font-family: var(--font-mono);
    font-size: 12px;
    font-weight: 700;
    margin-bottom: 10px;
  }
  .specs-step-title {
    margin: 0 0 4px;
    font-family: var(--font-display);
    font-size: 13.5px;
    font-weight: 700;
    color: var(--text-strong);
    letter-spacing: -0.005em;
  }
  .specs-step-body {
    margin: 0;
    font-size: 12.5px;
    color: var(--text-muted);
    line-height: 1.5;
  }
  .specs-step-body code {
    font-family: var(--font-mono);
    font-size: 11.5px;
    background: rgba(255,255,255,0.04);
    padding: 1px 5px;
    border-radius: 4px;
    color: var(--text);
  }

  /* ─── 403 / not-found ─── */
  .specs-empty {
    max-width: 540px;
    margin: var(--space-8) auto;
    padding: var(--space-6);
    text-align: center;
    background: var(--bg-elevated);
    border: 1px dashed var(--border-strong);
    border-radius: 16px;
  }
  .specs-empty h2 {
    font-family: var(--font-display);
    font-size: 20px;
    margin: 0 0 8px;
    color: var(--text-strong);
  }
  .specs-empty p {
    margin: 0;
    color: var(--text-muted);
    font-size: 13.5px;
  }
`;

interface ResolvedRepo {
  ownerId: string;
  ownerUsername: string;
  repoId: string;
  repoName: string;
  defaultBranch: string;
}

async function resolveRepo(
  ownerName: string,
  repoName: string
): Promise<ResolvedRepo | null> {
  try {
    const [ownerRow] = await db
      .select()
      .from(users)
      .where(eq(users.username, ownerName))
      .limit(1);
    if (!ownerRow) return null;
    const [repoRow] = await db
      .select()
      .from(repositories)
      .where(
        and(
          eq(repositories.ownerId, ownerRow.id),
          eq(repositories.name, repoName)
        )
      )
      .limit(1);
    if (!repoRow) return null;
    return {
      ownerId: ownerRow.id,
      ownerUsername: ownerRow.username,
      repoId: repoRow.id,
      repoName: repoRow.name,
      defaultBranch: repoRow.defaultBranch || "main",
    };
  } catch {
    return null;
  }
}

/**
 * Write access check. Gluecron has no collaborator table yet, so "write
 * access" == repo owner. Matches the convention used by repo-settings and
 * ai-explain's regenerate endpoint.
 */
function hasWriteAccess(
  resolved: ResolvedRepo,
  userId: string | undefined
): boolean {
  return !!userId && resolved.ownerId === userId;
}

/**
 * Build the default spec text for an issue-driven generation. Format:
 *
 *   Implement: <title>
 *
 *   <body>
 *
 *   Closes #<n>
 *
 * The trailing `Closes #N` is picked up by `src/lib/close-keywords.ts` (J7)
 * so the issue auto-closes when the AI-generated PR is merged. Body is
 * trimmed and falls back to an empty string if missing. Pure helper —
 * exported for tests.
 */
export function buildSpecFromIssue(input: {
  number: number;
  title: string;
  body: string | null | undefined;
}): string {
  const title = (input.title || "").trim();
  const body = (input.body || "").trim();
  const lines: string[] = [];
  if (title) lines.push(`Implement: ${title}`);
  if (body) {
    lines.push("");
    lines.push(body);
  }
  lines.push("");
  lines.push(`Closes #${input.number}`);
  return lines.join("\n");
}

function SpecForm({
  ownerName,
  repoName,
  branches,
  defaultBranch,
  spec,
  baseRef,
  error,
  fromIssueNumber,
  fromIssueTitle,
}: {
  ownerName: string;
  repoName: string;
  branches: string[];
  defaultBranch: string;
  spec?: string;
  baseRef?: string;
  error?: string;
  fromIssueNumber?: number;
  fromIssueTitle?: string;
}) {
  const branchList = branches.length > 0 ? branches : [defaultBranch];
  const selectedBase = baseRef && branchList.includes(baseRef)
    ? baseRef
    : defaultBranch;
  return (
    <div class="specs-wrap">
      <header class="specs-head">
        <div class="specs-eyebrow">
          <span class="specs-eyebrow-dot" aria-hidden="true" />
          Repository · Spec to PR
          <span class="specs-pill-experimental">Experimental</span>
        </div>
        <h1 class="specs-title">
          <span class="specs-title-grad">Describe it. Ship a draft.</span>
        </h1>
        <p class="specs-sub">
          Write a feature in plain English. Claude drafts the code changes
          and opens a pull request against the branch you pick. Every PR is{" "}
          <strong>draft by default</strong> — review every line before merging.
        </p>
      </header>

      {fromIssueNumber && (
        <div class="specs-banner is-info" role="status">
          <span class="specs-banner-dot" aria-hidden="true" />
          <span>
            Building from issue{" "}
            <a href={`/${ownerName}/${repoName}/issues/${fromIssueNumber}`}>
              #{fromIssueNumber}
              {fromIssueTitle ? ` — ${fromIssueTitle}` : ""}
            </a>
            . The spec below has been pre-filled and will auto-close the
            issue on merge.
          </span>
        </div>
      )}

      {error && (
        <div class="specs-banner is-error" role="alert">
          <span class="specs-banner-dot" aria-hidden="true" />
          <span>{error}</span>
        </div>
      )}

      <section class="specs-section">
        <header class="specs-section-head">
          <h2 class="specs-section-title">Feature spec</h2>
          <p class="specs-section-sub">
            One sentence or a paragraph. Be specific about files, behaviour,
            or success criteria when you can.
          </p>
        </header>
        <div class="specs-section-body">
          <form
            method="post"
            action={`/${ownerName}/${repoName}/spec`}
            id="spec-form"
          >
            <div class="specs-field">
              <label class="specs-field-label" for="spec">What do you want built?</label>
              <textarea
                class="specs-textarea"
                name="spec"
                id="spec"
                rows={10}
                required
                placeholder="add a dark mode toggle to the settings page"
              >{spec || ""}</textarea>
            </div>

            <div class="specs-field">
              <label class="specs-field-label" for="baseRef">Base branch</label>
              <select
                class="specs-select"
                name="baseRef"
                id="baseRef"
                value={selectedBase}
              >
                {branchList.map((b) => (
                  <option value={b} selected={b === selectedBase}>
                    {b}
                  </option>
                ))}
              </select>
              <p class="specs-field-hint">
                The draft PR will target this branch. Nothing lands without
                your approval.
              </p>
            </div>

            <div class="specs-actions">
              <button type="submit" class="specs-btn specs-btn-primary">
                Generate PR with AI
              </button>
              <span class="specs-actions-hint">Typically 10-30 seconds.</span>
            </div>
          </form>
        </div>
      </section>

      <section class="specs-section">
        <header class="specs-section-head">
          <h2 class="specs-section-title">How this works</h2>
          <p class="specs-section-sub">
            Three steps from spec to mergeable diff — all observable, all
            reversible.
          </p>
        </header>
        <div class="specs-section-body">
          <div class="specs-steps">
            <div class="specs-step">
              <span class="specs-step-num">1</span>
              <h3 class="specs-step-title">You write a spec.</h3>
              <p class="specs-step-body">
                A sentence or a paragraph describing the change you want.
              </p>
            </div>
            <div class="specs-step">
              <span class="specs-step-num">2</span>
              <h3 class="specs-step-title">Claude drafts the diff.</h3>
              <p class="specs-step-body">
                We fetch the base branch, run Claude against the repo, and
                commit the proposed changes to a new branch.
              </p>
            </div>
            <div class="specs-step">
              <span class="specs-step-num">3</span>
              <h3 class="specs-step-title">A draft PR opens.</h3>
              <p class="specs-step-body">
                You review, edit, and merge on your terms. Nothing lands on{" "}
                <code>{selectedBase}</code> automatically.
              </p>
            </div>
          </div>
        </div>
      </section>

      <script dangerouslySetInnerHTML={{ __html: DISABLE_ON_SUBMIT_JS }} />
      <style dangerouslySetInnerHTML={{ __html: specsStyles }} />
    </div>
  );
}

specs.get("/:owner/:repo/spec", softAuth, requireAuth, async (c) => {
  const { owner, repo } = c.req.param();
  const user = c.get("user")!;

  const resolved = await resolveRepo(owner, repo);
  if (!resolved) {
    return c.html(
      <Layout title="Not Found" user={user}>
        <div class="specs-empty">
          <h2>Repository not found</h2>
          <p>No such repository.</p>
        </div>
        <style dangerouslySetInnerHTML={{ __html: specsStyles }} />
      </Layout>,
      404
    );
  }

  if (!hasWriteAccess(resolved, user.id)) {
    return c.html(
      <Layout title="Forbidden" user={user}>
        <RepoHeader owner={owner} repo={repo} />
        <div class="specs-empty">
          <h2>Write access required</h2>
          <p>You need write access to generate a spec-to-PR on this repository.</p>
        </div>
        <style dangerouslySetInnerHTML={{ __html: specsStyles }} />
      </Layout>,
      403
    );
  }

  let branches: string[] = [];
  try {
    branches = await listBranches(owner, repo);
  } catch {
    branches = [];
  }

  // Optional: pre-fill from an issue. Triggered from the "Build with AI"
  // button on the issue detail page. Silently no-ops on missing/unknown
  // issue so the form still renders.
  let prefilledSpec: string | undefined;
  let fromIssueNumber: number | undefined;
  let fromIssueTitle: string | undefined;
  const fromIssueRaw = c.req.query("fromIssue");
  if (fromIssueRaw) {
    const n = Number.parseInt(fromIssueRaw, 10);
    if (Number.isInteger(n) && n > 0) {
      try {
        const [issueRow] = await db
          .select()
          .from(issues)
          .where(
            and(eq(issues.repositoryId, resolved.repoId), eq(issues.number, n))
          )
          .limit(1);
        if (issueRow) {
          fromIssueNumber = issueRow.number;
          fromIssueTitle = issueRow.title;
          prefilledSpec = buildSpecFromIssue({
            number: issueRow.number,
            title: issueRow.title,
            body: issueRow.body,
          });
        }
      } catch {
        // Pre-fill is a convenience, never block form render.
      }
    }
  }

  return c.html(
    <Layout title={`Spec to PR — ${owner}/${repo}`} user={user}>
      <RepoHeader owner={owner} repo={repo} />
      <SpecForm
        ownerName={owner}
        repoName={repo}
        branches={branches}
        defaultBranch={resolved.defaultBranch}
        spec={prefilledSpec}
        fromIssueNumber={fromIssueNumber}
        fromIssueTitle={fromIssueTitle}
      />
    </Layout>
  );
});

specs.post("/:owner/:repo/spec", softAuth, requireAuth, async (c) => {
  const { owner, repo } = c.req.param();
  const user = c.get("user")!;

  const resolved = await resolveRepo(owner, repo);
  if (!resolved) return c.notFound();

  if (!hasWriteAccess(resolved, user.id)) {
    return c.html(
      <Layout title="Forbidden" user={user}>
        <RepoHeader owner={owner} repo={repo} />
        <div class="specs-empty">
          <h2>Write access required</h2>
          <p>You need write access to generate a spec-to-PR on this repository.</p>
        </div>
        <style dangerouslySetInnerHTML={{ __html: specsStyles }} />
      </Layout>,
      403
    );
  }

  const body = await c.req.parseBody();
  const spec = String(body.spec || "").trim();
  const baseRef = String(body.baseRef || resolved.defaultBranch).trim()
    || resolved.defaultBranch;

  let branches: string[] = [];
  try {
    branches = await listBranches(owner, repo);
  } catch {
    branches = [];
  }

  function renderWithError(error: string, status: 400 | 500 | 503 = 400) {
    return c.html(
      <Layout title={`Spec to PR — ${owner}/${repo}`} user={user}>
        <RepoHeader owner={owner} repo={repo} />
        <SpecForm
          ownerName={owner}
          repoName={repo}
          branches={branches}
          defaultBranch={resolved!.defaultBranch}
          spec={spec}
          baseRef={baseRef}
          error={error}
        />
      </Layout>,
      status
    );
  }

  if (!spec) {
    return renderWithError("Spec is required.");
  }

  // Dynamically import the backend so this file works even before the
  // sibling branch landing `src/lib/spec-to-pr.ts` is merged. If the module
  // is missing or throws we surface a soft error instead of 500-ing.
  let createSpecPR:
    | ((args: {
        repoId: string;
        spec: string;
        baseRef: string;
        userId: string;
      }) => Promise<
        | { ok: true; prNumber: number }
        | { ok: false; error: string }
      >)
    | null = null;
  try {
    const mod: any = await import("../lib/spec-to-pr");
    createSpecPR =
      (mod && (mod.createSpecPR || (mod.default && mod.default.createSpecPR))) ||
      null;
  } catch {
    createSpecPR = null;
  }

  if (!createSpecPR) {
    return renderWithError(
      "Backend not available — spec-to-PR is not deployed yet. Please try again later.",
      503
    );
  }

  // Kick off the spec job in the background and redirect to the live
  // progress page immediately. This means the user sees a live timeline
  // rather than staring at a browser spinner for 10-30s.
  const jobId = crypto.randomUUID().replace(/-/g, "").slice(0, 12);
  const job: SpecJob = {
    id: jobId,
    owner,
    repo,
    stage: "queued",
    label: STAGE_LABELS.queued,
    prNumber: null,
    error: null,
    startedAt: Date.now(),
    completedAt: null,
  };
  specJobs.set(jobId, job);

  // Fire and forget — never await so the response is immediate.
  void runSpecJobInBackground(job, {
    repoId: resolved.repoId,
    spec,
    baseRef,
    userId: user.id,
  });

  return c.redirect(`/${owner}/${repo}/spec/${jobId}/progress`);
});

// ─── Spec progress routes ───────────────────────────────────────────────────
//
//   GET  /:owner/:repo/spec/:jobId/progress          — HTML progress page
//   GET  /:owner/:repo/spec/:jobId/progress/events   — SSE stream
//   GET  /:owner/:repo/spec/:jobId/status            — JSON polling endpoint

const progressStyles = `
  .sp-wrap {
    max-width: 640px;
    margin: 0 auto;
    padding: var(--space-8) var(--space-4);
  }
  .sp-head {
    margin-bottom: var(--space-6);
    text-align: center;
  }
  .sp-eyebrow {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    text-transform: uppercase;
    font-family: var(--font-mono);
    font-size: 11px;
    letter-spacing: 0.16em;
    color: var(--text-muted);
    font-weight: 600;
    margin-bottom: 10px;
  }
  .sp-title {
    font-family: var(--font-display);
    font-size: clamp(22px, 3vw, 30px);
    font-weight: 800;
    letter-spacing: -0.024em;
    color: var(--text-strong);
    margin: 0 0 8px;
  }
  .sp-sub {
    font-size: 13px;
    color: var(--text-muted);
    margin: 0;
  }
  /* ── Timeline ── */
  .sp-timeline {
    position: relative;
    padding: 0;
    list-style: none;
    margin: 0;
  }
  .sp-timeline::before {
    content: '';
    position: absolute;
    left: 20px;
    top: 12px;
    bottom: 12px;
    width: 1px;
    background: var(--border);
  }
  .sp-step {
    position: relative;
    display: flex;
    align-items: flex-start;
    gap: 16px;
    padding: 12px 0;
  }
  .sp-dot {
    flex-shrink: 0;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 16px;
    background: var(--bg-elevated);
    border: 2px solid var(--border);
    position: relative;
    z-index: 1;
    transition: border-color 300ms ease, background 300ms ease;
  }
  .sp-dot.is-done {
    border-color: #22c55e;
    background: rgba(34,197,94,0.12);
  }
  .sp-dot.is-active {
    border-color: #8c6dff;
    background: rgba(140,109,255,0.14);
    animation: sp-pulse 1.6s ease-in-out infinite;
  }
  .sp-dot.is-error {
    border-color: #f87171;
    background: rgba(248,113,113,0.12);
  }
  @keyframes sp-pulse {
    0%, 100% { box-shadow: 0 0 0 0 rgba(140,109,255,0.35); }
    50%       { box-shadow: 0 0 0 8px rgba(140,109,255,0); }
  }
  .sp-step-body {
    padding-top: 8px;
  }
  .sp-step-label {
    font-size: 14px;
    font-weight: 600;
    color: var(--text-muted);
    transition: color 300ms ease;
  }
  .sp-step-label.is-done   { color: #22c55e; }
  .sp-step-label.is-active { color: var(--text-strong); }
  .sp-step-label.is-error  { color: #f87171; }
  .sp-step-detail {
    font-size: 12px;
    color: var(--text-muted);
    margin-top: 2px;
    font-family: var(--font-mono);
  }
  /* ── Done card ── */
  .sp-done-card {
    margin-top: var(--space-5);
    padding: 20px 24px;
    background: rgba(34,197,94,0.08);
    border: 1px solid rgba(34,197,94,0.30);
    border-radius: 14px;
    text-align: center;
    display: none;
  }
  .sp-done-card.is-visible { display: block; }
  .sp-done-card h2 {
    font-family: var(--font-display);
    font-size: 18px;
    font-weight: 700;
    color: #22c55e;
    margin: 0 0 8px;
  }
  .sp-done-card p {
    font-size: 13px;
    color: var(--text-muted);
    margin: 0 0 14px;
  }
  .sp-done-link {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 10px 20px;
    background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
    color: #fff;
    border-radius: 10px;
    font-size: 13.5px;
    font-weight: 600;
    text-decoration: none;
  }
  .sp-done-link:hover { opacity: 0.92; text-decoration: none; }
  /* ── Error card ── */
  .sp-error-card {
    margin-top: var(--space-5);
    padding: 16px 20px;
    background: rgba(248,113,113,0.08);
    border: 1px solid rgba(248,113,113,0.30);
    border-radius: 14px;
    display: none;
  }
  .sp-error-card.is-visible { display: block; }
  .sp-error-card p {
    font-size: 13px;
    color: #fca5a5;
    margin: 0 0 10px;
  }
  .sp-error-card a {
    font-size: 13px;
    color: #f87171;
    text-decoration: underline;
  }
`;

/** Inline JS for the progress page — polls /status every 2s. ~18 lines. */
const PROGRESS_POLL_JS = `
(function() {
  var stages = ['queued','analyzing','writing','opening_pr','done','error'];
  var url = location.pathname.replace(/\\/progress$/, '/status');
  function update(d) {
    stages.forEach(function(s) {
      var dot = document.getElementById('dot-' + s);
      var lbl = document.getElementById('lbl-' + s);
      if (!dot || !lbl) return;
      dot.className = 'sp-dot';
      lbl.className = 'sp-step-label';
      var si = stages.indexOf(s), di = stages.indexOf(d.stage);
      if (si < di) { dot.className += ' is-done'; lbl.className += ' is-done'; }
      else if (s === d.stage && s !== 'error') { dot.className += ' is-active'; lbl.className += ' is-active'; }
      else if (s === 'error' && d.stage === 'error') { dot.className += ' is-error'; lbl.className += ' is-error'; }
    });
    if (d.stage === 'done' && d.prNumber) {
      var c = document.getElementById('sp-done-card');
      var lk = document.getElementById('sp-pr-link');
      if (c) c.className = 'sp-done-card is-visible';
      if (lk) lk.href = lk.dataset.base + '/' + d.prNumber;
    }
    if (d.stage === 'error') {
      var ec = document.getElementById('sp-error-card');
      var em = document.getElementById('sp-error-msg');
      if (ec) ec.className = 'sp-error-card is-visible';
      if (em) em.textContent = d.error || 'Unknown error.';
    }
    if (d.stage !== 'done' && d.stage !== 'error') { setTimeout(poll, 2000); }
  }
  function poll() {
    fetch(url).then(function(r){ return r.json(); }).then(update).catch(function(){ setTimeout(poll, 3000); });
  }
  poll();
})();
`;

/** The 4 pipeline steps shown on the progress page (excluding queued). */
const PIPELINE_STEPS: Array<{ stage: SpecStage; label: string; icon: string }> = [
  { stage: "analyzing", label: "Analyzing spec", icon: "🔍" },
  { stage: "writing", label: "Writing code", icon: "✍️" },
  { stage: "opening_pr", label: "Opening PR", icon: "📬" },
  { stage: "done", label: "Done", icon: "✅" },
];

function ProgressPage({
  owner,
  repo,
  job,
}: {
  owner: string;
  repo: string;
  jobId: string;
  job: SpecJob;
}) {
  const stageIdx = (s: SpecStage) => {
    const order: SpecStage[] = ["queued", "analyzing", "writing", "opening_pr", "done", "error"];
    return order.indexOf(s);
  };
  const curIdx = stageIdx(job.stage);

  return (
    <div class="sp-wrap">
      <header class="sp-head">
        <div class="sp-eyebrow">Spec to PR · Live progress</div>
        <h1 class="sp-title">Building your PR…</h1>
        <p class="sp-sub">Sit tight — Claude is generating the implementation.</p>
      </header>

      <ul class="sp-timeline">
        {PIPELINE_STEPS.map(({ stage, label, icon }) => {
          const sIdx = stageIdx(stage);
          const isDone = curIdx > sIdx || (job.stage === "done" && stage === "done");
          const isActive = job.stage === stage;
          const isError = job.stage === "error" && stage === "writing"; // show error on writing step
          let dotClass = "sp-dot";
          let lblClass = "sp-step-label";
          if (isDone) { dotClass += " is-done"; lblClass += " is-done"; }
          else if (isActive) { dotClass += " is-active"; lblClass += " is-active"; }
          else if (isError) { dotClass += " is-error"; lblClass += " is-error"; }

          return (
            <li class="sp-step">
              <div id={`dot-${stage}`} class={dotClass}>{icon}</div>
              <div class="sp-step-body">
                <div id={`lbl-${stage}`} class={lblClass}>{label}</div>
              </div>
            </li>
          );
        })}
        {/* always show the error stage dot so JS can target it */}
        <li class="sp-step" id="step-error" style={job.stage === "error" ? "" : "display:none"}>
          <div id="dot-error" class={`sp-dot${job.stage === "error" ? " is-error" : ""}`}>❌</div>
          <div class="sp-step-body">
            <div id="lbl-error" class={`sp-step-label${job.stage === "error" ? " is-error" : ""}`}>Error</div>
          </div>
        </li>
      </ul>

      {/* Done card — hidden until JS reveals it */}
      <div
        id="sp-done-card"
        class={`sp-done-card${job.stage === "done" ? " is-visible" : ""}`}
      >
        <h2>PR opened!</h2>
        {job.completedAt && job.startedAt && (
          <p>
            Merged in {Math.round((job.completedAt - job.startedAt) / 1000)}s
          </p>
        )}
        <a
          id="sp-pr-link"
          class="sp-done-link"
          href={job.prNumber ? `/${owner}/${repo}/pulls/${job.prNumber}` : "#"}
          data-base={`/${owner}/${repo}/pulls`}
        >
          View PR {job.prNumber ? `#${job.prNumber}` : ""}
        </a>
      </div>

      {/* Error card */}
      <div
        id="sp-error-card"
        class={`sp-error-card${job.stage === "error" ? " is-visible" : ""}`}
      >
        <p id="sp-error-msg">{job.error || ""}</p>
        <a href={`/${owner}/${repo}/spec`}>Try again</a>
      </div>

      <script dangerouslySetInnerHTML={{ __html: PROGRESS_POLL_JS }} />
      <style dangerouslySetInnerHTML={{ __html: progressStyles }} />
    </div>
  );
}

// GET /:owner/:repo/spec/:jobId/progress — HTML progress page
specs.get("/:owner/:repo/spec/:jobId/progress", softAuth, requireAuth, async (c) => {
  const { owner, repo, jobId } = c.req.param();
  const user = c.get("user")!;

  const resolved = await resolveRepo(owner, repo);
  if (!resolved) return c.notFound();
  if (!hasWriteAccess(resolved, user.id)) return c.text("Forbidden", 403);

  const job = specJobs.get(jobId);
  if (!job) {
    // Job expired or unknown — redirect to spec form.
    return c.redirect(`/${owner}/${repo}/spec`);
  }

  // If already done, redirect straight to the PR.
  if (job.stage === "done" && job.prNumber) {
    return c.redirect(`/${owner}/${repo}/pulls/${job.prNumber}`);
  }

  return c.html(
    <Layout title={`Generating PR — ${owner}/${repo}`} user={user}>
      <RepoHeader owner={owner} repo={repo} />
      <ProgressPage owner={owner} repo={repo} jobId={jobId} job={job} />
    </Layout>
  );
});

// GET /:owner/:repo/spec/:jobId/progress/events — SSE stream
specs.get("/:owner/:repo/spec/:jobId/progress/events", softAuth, requireAuth, async (c) => {
  const { owner, repo, jobId } = c.req.param();
  const user = c.get("user")!;

  const resolved = await resolveRepo(owner, repo);
  if (!resolved) return c.json({ error: "Not found" }, 404);
  if (!hasWriteAccess(resolved, user.id)) return c.json({ error: "Forbidden" }, 403);

  const job = specJobs.get(jobId);
  if (!job) return c.json({ error: "Job not found" }, 404);

  const topic = specJobTopic(jobId);
  const encoder = new TextEncoder();

  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      let closed = false;
      const safeEnqueue = (chunk: string) => {
        if (closed) return;
        try { controller.enqueue(encoder.encode(chunk)); } catch { closed = true; }
      };

      safeEnqueue(": open\n\n");

      // Send current state immediately so late connectors get a snapshot.
      const snapJob = specJobs.get(jobId);
      if (snapJob) {
        const payload = JSON.stringify({ stage: snapJob.stage, label: snapJob.label, prNumber: snapJob.prNumber, error: snapJob.error });
        safeEnqueue(`event: stage\ndata: ${payload}\n\n`);
      }

      const unsubscribe = subscribe(topic, (ev) => {
        let out = "";
        if (ev.event) out += `event: ${ev.event}\n`;
        const data = typeof ev.data === "string" ? ev.data : JSON.stringify(ev.data);
        for (const line of data.split("\n")) out += `data: ${line}\n`;
        out += "\n";
        safeEnqueue(out);
      });

      const ping = setInterval(() => safeEnqueue(": ping\n\n"), 25_000);

      const cleanup = () => {
        if (closed) return;
        closed = true;
        clearInterval(ping);
        unsubscribe();
        try { controller.close(); } catch { /* already closed */ }
      };

      const signal = c.req.raw.signal;
      if (signal) {
        if (signal.aborted) cleanup();
        else signal.addEventListener("abort", cleanup, { once: true });
      }
    },
  });

  return new Response(stream, {
    status: 200,
    headers: {
      "Content-Type": "text/event-stream; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      "Connection": "keep-alive",
      "X-Accel-Buffering": "no",
    },
  });
});

// GET /:owner/:repo/spec/:jobId/status — JSON polling endpoint
specs.get("/:owner/:repo/spec/:jobId/status", softAuth, requireAuth, async (c) => {
  const { owner, repo, jobId } = c.req.param();
  const user = c.get("user")!;

  const resolved = await resolveRepo(owner, repo);
  if (!resolved) return c.json({ error: "Not found" }, 404);
  if (!hasWriteAccess(resolved, user.id)) return c.json({ error: "Forbidden" }, 403);

  const job = specJobs.get(jobId);
  if (!job) return c.json({ error: "Job not found or expired" }, 404);

  return c.json({
    jobId: job.id,
    stage: job.stage,
    label: job.label,
    prNumber: job.prNumber,
    error: job.error,
    startedAt: job.startedAt,
    completedAt: job.completedAt,
  });
});

// ─── GET /specs — dashboard listing all specs across the user's repos ──────
//
// Walks every repo the signed-in user owns, looks at `.gluecron/specs/*.md`
// on the default branch, parses the front-matter for `status:` + `title:`,
// and surfaces a flat list with linked PR (when one exists). Soft-fails on
// any repo that can't be scanned — the dashboard still renders.

interface SpecRow {
  ownerName: string;
  repoName: string;
  specPath: string;
  title: string;
  status: SpecStatus;
  prNumber: number | null;
}

async function collectSpecsForOwner(ownerId: string): Promise<SpecRow[]> {
  let owner: { username: string } | undefined;
  try {
    const [row] = await db
      .select({ username: users.username })
      .from(users)
      .where(eq(users.id, ownerId))
      .limit(1);
    owner = row;
  } catch {
    return [];
  }
  if (!owner) return [];

  let repos: Array<{ id: string; name: string; defaultBranch: string }> = [];
  try {
    repos = await db
      .select({
        id: repositories.id,
        name: repositories.name,
        defaultBranch: repositories.defaultBranch,
      })
      .from(repositories)
      .where(
        and(eq(repositories.ownerId, ownerId), eq(repositories.isArchived, false))
      )
      .limit(100);
  } catch {
    return [];
  }

  const out: SpecRow[] = [];
  for (const repo of repos) {
    const branch = repo.defaultBranch || "main";
    let paths: string[] = [];
    try {
      const tree = await getTreeRecursive(owner.username, repo.name, branch, 5000);
      if (!tree) continue;
      paths = tree.tree
        .filter(
          (e) =>
            e.type === "blob" &&
            e.path.startsWith(".gluecron/specs/") &&
            e.path.toLowerCase().endsWith(".md")
        )
        .map((e) => e.path);
    } catch {
      continue;
    }
    for (const p of paths) {
      let content = "";
      try {
        const blob = await getBlob(owner.username, repo.name, branch, p);
        if (!blob || blob.isBinary) continue;
        content = blob.content;
      } catch {
        continue;
      }
      const parsed = parseFrontMatter(content);
      const title =
        (parsed.frontMatter.title && parsed.frontMatter.title.trim()) ||
        (p.split("/").pop() || p).replace(/\.md$/i, "");
      const statusRaw = (parsed.frontMatter.status || "draft").toLowerCase();
      const status: SpecStatus =
        statusRaw === "draft" ||
        statusRaw === "ready" ||
        statusRaw === "building" ||
        statusRaw === "shipped" ||
        statusRaw === "failed"
          ? (statusRaw as SpecStatus)
          : "draft";

      // Best-effort PR lookup: any PR whose body mentions the spec path
      // and carries the spec marker. Newest first.
      let prNumber: number | null = null;
      try {
        const [pr] = await db
          .select({ number: pullRequests.number })
          .from(pullRequests)
          .where(
            and(
              eq(pullRequests.repositoryId, repo.id),
              like(pullRequests.body, `%${AI_SPEC_PR_MARKER}%`),
              like(pullRequests.body, `%${p}%`)
            )
          )
          .orderBy(pullRequests.createdAt)
          .limit(1);
        if (pr) prNumber = pr.number;
      } catch {
        prNumber = null;
      }

      out.push({
        ownerName: owner.username,
        repoName: repo.name,
        specPath: p,
        title,
        status,
        prNumber,
      });
    }
  }
  return out;
}

specs.get("/specs", softAuth, requireAuth, async (c) => {
  const user = c.get("user")!;
  const rows = await collectSpecsForOwner(user.id);

  const byStatus = (s: SpecStatus) => rows.filter((r) => r.status === s);

  const statusBadgeColors: Record<SpecStatus, string> = {
    draft: "rgba(148,163,184,0.16)",
    ready: "rgba(54,197,214,0.18)",
    building: "rgba(140,109,255,0.20)",
    shipped: "rgba(34,197,94,0.18)",
    failed: "rgba(248,113,113,0.18)",
  };

  return c.html(
    <Layout title="Specs — Gluecron" user={user}>
      <div class="specs-wrap">
        <header class="specs-head">
          <div class="specs-eyebrow">
            <span class="specs-eyebrow-dot" aria-hidden="true" />
            Account · Specs dashboard
            <span class="specs-pill-experimental">Experimental</span>
          </div>
          <h1 class="specs-title">
            <span class="specs-title-grad">Your spec library.</span>
          </h1>
          <p class="specs-sub">
            Every <code>.gluecron/specs/*.md</code> file across your
            repositories. Set a spec's front-matter to{" "}
            <code>status: ready</code> and the autopilot picks it up within
            two minutes to open an implementation PR tagged{" "}
            <code>ai:spec-implementation</code>.
          </p>
        </header>

        <section class="specs-section">
          <header class="specs-section-head">
            <h2 class="specs-section-title">All specs ({rows.length})</h2>
            <p class="specs-section-sub">
              {byStatus("ready").length} ready · {byStatus("building").length}{" "}
              building · {byStatus("shipped").length} shipped ·{" "}
              {byStatus("failed").length} failed · {byStatus("draft").length}{" "}
              draft
            </p>
          </header>
          <div class="specs-section-body">
            {rows.length === 0 ? (
              <p class="specs-field-hint" style="font-size:13px;">
                No specs yet. Create a file like{" "}
                <code>.gluecron/specs/my-feature.md</code> in any of your
                repos with front-matter{" "}
                <code>---\ntitle: Add dark mode\nstatus: ready\n---</code> and
                it will land here.
              </p>
            ) : (
              <table style="width:100%;border-collapse:collapse;font-size:13px;">
                <thead>
                  <tr style="text-align:left;color:var(--text-muted);font-size:11px;text-transform:uppercase;letter-spacing:0.06em;">
                    <th style="padding:8px 4px;">Repo</th>
                    <th style="padding:8px 4px;">Title</th>
                    <th style="padding:8px 4px;">Status</th>
                    <th style="padding:8px 4px;">PR</th>
                    <th style="padding:8px 4px;">Path</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((r) => (
                    <tr style="border-top:1px solid var(--border);">
                      <td style="padding:10px 4px;">
                        <a href={`/${r.ownerName}/${r.repoName}`}>
                          {r.ownerName}/{r.repoName}
                        </a>
                      </td>
                      <td style="padding:10px 4px;color:var(--text-strong);">
                        {r.title}
                      </td>
                      <td style="padding:10px 4px;">
                        <span
                          style={`display:inline-block;padding:2px 8px;border-radius:9999px;font-family:var(--font-mono);font-size:11px;background:${statusBadgeColors[r.status]};color:var(--text);`}
                        >
                          {r.status}
                        </span>
                      </td>
                      <td style="padding:10px 4px;">
                        {r.prNumber ? (
                          <a
                            href={`/${r.ownerName}/${r.repoName}/pulls/${r.prNumber}`}
                          >
                            #{r.prNumber}
                          </a>
                        ) : (
                          <span style="color:var(--text-muted);">—</span>
                        )}
                      </td>
                      <td style="padding:10px 4px;font-family:var(--font-mono);font-size:11.5px;color:var(--text-muted);">
                        <a
                          href={`/${r.ownerName}/${r.repoName}/blob/main/${r.specPath}`}
                        >
                          {r.specPath}
                        </a>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </section>

        <style dangerouslySetInnerHTML={{ __html: specsStyles }} />
      </div>
    </Layout>
  );
});

export default specs;
